"""thoi khong chuyen nua

Revision ID: 01929a3df3fa
Revises: 82b343cf460a
Create Date: 2025-04-20 14:38:12.871014

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01929a3df3fa'
down_revision = '82b343cf460a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversationmessage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversationmessage',
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('usage_tokens', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rewrite_question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('report', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='conversationmessage_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conversationmessage_pkey')
    )
    # ### end Alembic commands ###
