"""add pay time

Revision ID: 03568089cfe3
Revises: 2a0edf7133a2
Create Date: 2025-04-14 22:36:32.137889

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '03568089cfe3'
down_revision = '2a0edf7133a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topuphistory', sa.Column('pay_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topuphistory', 'pay_date')
    # ### end Alembic commands ###
