"""add status for document model

Revision ID: 06c198a62e6b
Revises: d2139635090c
Create Date: 2025-03-22 12:16:04.338299

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '06c198a62e6b'
down_revision = 'd2139635090c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'status')
    # ### end Alembic commands ###
