"""convert from mongodb

Revision ID: 09e3f5d9803c
Revises: 93d5831c4dbd
Create Date: 2025-04-20 14:24:27.721322

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '09e3f5d9803c'
down_revision = '93d5831c4dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversationmessage', sa.Column('report', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversationmessage', 'report')
    # ### end Alembic commands ###
