"""fix payment

Revision ID: 0d36f5c24461
Revises: cc9c5f75a38c
Create Date: 2025-04-15 11:49:58.128347

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0d36f5c24461'
down_revision = 'cc9c5f75a38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('remaining_tokens', sa.BigInteger(), nullable=True))
    op.add_column('topuphistory', sa.Column('chatbot_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'topuphistory', 'chatbot', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'remaining_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('remaining_tokens', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'topuphistory', type_='foreignkey')
    op.drop_column('topuphistory', 'chatbot_id')
    op.drop_column('chatbot', 'remaining_tokens')
    # ### end Alembic commands ###
