"""add favorite messages

Revision ID: 1971c3091bcf
Revises: 7bcf27555dd0
Create Date: 2025-04-11 23:16:17.968867

"""
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1971c3091bcf'
down_revision = '7bcf27555dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritemessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chatbot_response_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frequentlyaskedquestion', sa.Column('embedding', pgvector.sqlalchemy.VECTOR(dim=3072), autoincrement=False, nullable=True))
    op.drop_table('favoritemessage')
    # ### end Alembic commands ###
