"""add usage token to document table

Revision ID: 1de52336a592
Revises: 6db8f3c2215f
Create Date: 2025-04-14 08:36:12.849890

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1de52336a592'
down_revision = '6db8f3c2215f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('usage_tokens', sa.Integer(), nullable=True))
    op.execute("UPDATE document SET usage_tokens = 0 WHERE usage_tokens IS NULL")
    op.execute("UPDATE document SET has_qa_data = false WHERE has_qa_data IS NULL")
    op.alter_column(table_name='document', column_name='usage_tokens', nullable=False, server_default=sa.text('0'))
    op.alter_column(table_name='document', column_name='has_qa_data', nullable=False, server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'has_qa_data', nullable=True)
    op.drop_column('document', 'usage_tokens')
    # ### end Alembic commands ###
