"""set is_first_login not nullable

Revision ID: 21bbff888a2f
Revises: a03bc447887c
Create Date: 2025-03-02 22:53:01.897437

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21bbff888a2f'
down_revision = 'a03bc447887c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
