"""add is_deleted column to table Conversation

Revision ID: 23b3d9946177
Revises: 06c198a62e6b
Create Date: 2025-03-29 19:00:07.738816

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '23b3d9946177'
down_revision = '06c198a62e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'is_deleted')
    # ### end Alembic commands ###
