"""update column usage_tokens int -> bigint

Revision ID: 457f21fe0590
Revises: a31894f34e65
Create Date: 2025-04-16 02:01:19.777809

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '457f21fe0590'
down_revision = 'a31894f34e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot', 'total_usage_token',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('document', 'usage_tokens',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('topuphistory', 'tokens_received',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topuphistory', 'tokens_received',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('document', 'usage_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chatbot', 'total_usage_token',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
