from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '50caf8e4ab78'
down_revision = '548dfba276b6'
branch_labels = None
depends_on = None


def upgrade():
    # Thêm cột nhưng cho phép NULL ban đầu
    op.add_column("user", sa.Column("is_chatbot_creator", sa.Boolean(), nullable=True))

    # Cập nhật tất cả giá trị NULL thành False
    op.execute("UPDATE \"user\" SET is_chatbot_creator = FALSE")

    # Đặt lại cột thành NOT NULL
    op.alter_column("user", "is_chatbot_creator", nullable=False)

    op.drop_table('item')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_chatbot_creator")
    # ### end Alembic commands ###
