"""add answer_if_no_data_provided field default value

Revision ID: 5680916f5713
Revises: 66fb8bf6b25e
Create Date: 2025-02-21 13:37:58.279416

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5680916f5713'
down_revision = '66fb8bf6b25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('answer_if_no_data_provided', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'answer_if_no_data_provided')
    # ### end Alembic commands ###
