"""add field total_usage_token in Chatbot table

Revision ID: 5dd24cd3d6cc
Revises: 23b3d9946177
Create Date: 2025-04-02 09:36:31.946513

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5dd24cd3d6cc'
down_revision = '23b3d9946177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('total_usage_token', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'total_usage_token')
    # ### end Alembic commands ###
