"""make chatbot name and organization unique

Revision ID: 5eb45e015ca4
Revises: 457f21fe0590
Create Date: 2025-04-16 13:13:32.618073

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5eb45e015ca4'
down_revision = '457f21fe0590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_name_organization', 'chatbot', ['name', 'organization'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_name_organization', 'chatbot', type_='unique')
    # ### end Alembic commands ###
