"""convert from mongodb

Revision ID: 622afcc9966d
Revises: cc5b95703999
Create Date: 2025-04-20 14:11:16.297327

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '622afcc9966d'
down_revision = 'cc5b95703999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversationmessage',
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referenceofmessage',
    sa.Column('conversation_message_id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_tokens', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_message_id'], ['conversationmessage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referenceofmessage')
    op.drop_table('conversationmessage')
    # ### end Alembic commands ###
