"""create fqa model

Revision ID: 685804409584
Revises: 50caf8e4ab78
Create Date: 2025-02-21 10:25:51.168102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '685804409584'
down_revision = '50caf8e4ab78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
