"""add firstMsg field to Conversation

Revision ID: 6a7a1335fac8
Revises: 5dd24cd3d6cc
Create Date: 2025-04-03 22:55:58.167601

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a7a1335fac8'
down_revision = '5dd24cd3d6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot', 'total_usage_token',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.add_column('conversation', sa.Column('firstMsg', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'firstMsg')
    op.alter_column('chatbot', 'total_usage_token',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
