"""add column chatbot_id to favorite_messages

Revision ID: 6db8f3c2215f
Revises: 1971c3091bcf
Create Date: 2025-04-13 21:04:14.477591

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6db8f3c2215f'
down_revision = '1971c3091bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoritemessage', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('favoritemessage', sa.Column('chatbot_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'favoritemessage', 'chatbot', ['chatbot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritemessage', type_='foreignkey')
    op.drop_column('favoritemessage', 'chatbot_id')
    op.drop_column('favoritemessage', 'created_at')
    # ### end Alembic commands ###
