"""add embedding to FAQ

Revision ID: 7bcf27555dd0
Revises: b93632a9ccc5
Create Date: 2025-04-11 17:14:09.633119

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '7bcf27555dd0'
down_revision = 'b93632a9ccc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frequentlyaskedquestion', sa.Column('embedding', Vector(dim=3072), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frequentlyaskedquestion', 'embedding')
    # ### end Alembic commands ###
