"""convert from mongodb

Revision ID: 7fdb1fa746a3
Revises: 622afcc9966d
Create Date: 2025-04-20 14:15:24.334677

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7fdb1fa746a3'
down_revision = '622afcc9966d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
