"""thoi khong chuyen nua

Revision ID: 82b343cf460a
Revises: 09e3f5d9803c
Create Date: 2025-04-20 14:33:22.695694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '82b343cf460a'
down_revision = '09e3f5d9803c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
