"""convert from mongodb

Revision ID: 8cbe2eb39a53
Revises: 7fdb1fa746a3
Create Date: 2025-04-20 14:17:31.642031

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8cbe2eb39a53'
down_revision = '7fdb1fa746a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referenceofmessage')
    op.add_column('conversationmessage', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('conversationmessage', sa.Column('usage_tokens', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversationmessage', 'usage_tokens')
    op.drop_column('conversationmessage', 'source')
    op.create_table('referenceofmessage',
    sa.Column('conversation_message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('usage_tokens', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_message_id'], ['conversationmessage.id'], name='referenceofmessage_conversation_message_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_message_id', name='referenceofmessage_pkey')
    )
    # ### end Alembic commands ###
