"""convert from mongodb

Revision ID: 93d5831c4dbd
Revises: 8cbe2eb39a53
Create Date: 2025-04-20 14:18:46.959448

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '93d5831c4dbd'
down_revision = '8cbe2eb39a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversationmessage', sa.Column('rewrite_question', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversationmessage', 'rewrite_question')
    # ### end Alembic commands ###
