"""add is_first_login column into user

Revision ID: a03bc447887c
Revises: fcae09b9e400
Create Date: 2025-03-02 22:52:24.840564

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a03bc447887c'
down_revision = 'fcae09b9e400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_first_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_first_login')
    # ### end Alembic commands ###
