"""remove max length in checkout_url

Revision ID: a31894f34e65
Revises: 0d36f5c24461
Create Date: 2025-04-16 00:27:37.225989

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a31894f34e65'
down_revision = '0d36f5c24461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'remaining_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('remaining_tokens', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
