"""sửa field answer ì no data provided

Revision ID: ab6bc395ca09
Revises: 5680916f5713
Create Date: 2025-02-22 16:09:01.326593

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ab6bc395ca09'
down_revision = '5680916f5713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
