"""alter column first_msg

Revision ID: b8612040ec9b
Revises: 6a7a1335fac8
Create Date: 2025-04-03 23:23:31.597133

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b8612040ec9b'
down_revision = '6a7a1335fac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('first_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('conversation', 'firstMsg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('firstMsg', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('conversation', 'first_msg')
    # ### end Alembic commands ###
