"""add has_qa_data

Revision ID: b93632a9ccc5
Revises: b8612040ec9b
Create Date: 2025-04-10 18:50:00.235859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b93632a9ccc5'
down_revision = 'b8612040ec9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('has_qa_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'has_qa_data')
    # ### end Alembic commands ###
