"""add table token bundle, add column is_active and is_activate to chatbot

Revision ID: bb1701ba2666
Revises: 5eb45e015ca4
Create Date: 2025-04-16 20:17:45.559598

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bb1701ba2666'
down_revision = '5eb45e015ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenbundle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('token_amount', sa.BigInteger(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('chatbot', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('chatbot', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'is_deleted')
    op.drop_column('chatbot', 'is_active')
    op.drop_table('tokenbundle')
    # ### end Alembic commands ###
