"""Fix link UserChatbotLink table

Revision ID: c7648d461a61
Revises: 21bbff888a2f
Create Date: 2025-03-16 15:09:05.338294

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7648d461a61'
down_revision = '21bbff888a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('guard_rails', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('chatbot', sa.Column('quota_limit', sa.Integer(), nullable=False))
    op.add_column('chatbot', sa.Column('window_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('chatbot', sa.Column('window_size', sa.Integer(), nullable=False))
    op.drop_column('chatbot', 'answer_if_no_data_provided')
    op.add_column('userchatbotlink', sa.Column('usage_count', sa.Integer(), nullable=False))
    op.add_column('userchatbotlink', sa.Column('reset_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userchatbotlink', 'reset_time')
    op.drop_column('userchatbotlink', 'usage_count')
    op.add_column('chatbot', sa.Column('answer_if_no_data_provided', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chatbot', 'window_size')
    op.drop_column('chatbot', 'window_type')
    op.drop_column('chatbot', 'quota_limit')
    op.drop_column('chatbot', 'guard_rails')
    # ### end Alembic commands ###
