"""add time for document model, edit remaining tokens to bigint

Revision ID: cc9c5f75a38c
Revises: fc383d14e4c7
Create Date: 2025-04-15 08:44:04.128785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cc9c5f75a38c'
down_revision = 'fc383d14e4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('latest_modified', sa.DateTime(), nullable=True))
    op.add_column('topuphistory', sa.Column('checkout_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('user', 'remaining_tokens',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'remaining_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('topuphistory', 'checkout_url')
    op.drop_column('document', 'latest_modified')
    # ### end Alembic commands ###
