"""add default value for paydate

Revision ID: d8eca60c2b32
Revises: 03568089cfe3
Create Date: 2025-04-14 22:38:27.518383

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8eca60c2b32'
down_revision = '03568089cfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
