"""thêm temperature vào chatbot

Revision ID: e7a32c8c1efa
Revises: a0824e5ef03f
Create Date: 2025-02-19 15:47:16.177021

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e7a32c8c1efa'
down_revision = 'a0824e5ef03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('temperature', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'temperature')
    # ### end Alembic commands ###
