"""Update database schema

Revision ID: ec5ff2e05b38
Revises: ab6bc395ca09
Create Date: 2025-02-25 02:31:58.413400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ec5ff2e05b38'
down_revision = 'ab6bc395ca09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
