"""add bank_id column

Revision ID: fc383d14e4c7
Revises: 13f028b52db8
Create Date: 2025-04-14 23:15:06.197954

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc383d14e4c7'
down_revision = '13f028b52db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topuphistory', sa.Column('bank_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topuphistory', 'bank_id')
    # ### end Alembic commands ###
